
import { Wrap, WrapItem, VStack } from '@chakra-ui/react'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import ProductCard from '../components/Cards/ProductCard'
import Layout from '../components/Layout'
import SideBar from '../components/Layout/SideBar'
import { Pagination } from '../components/UI/Pagination'

export default function Home({ products }: any) {
  const [page, setPage] = useState(1);

  const pageStart = (Number(page) - 1) * Number(10);
  const pageEnd = pageStart + Number(10);

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [page])

  function slicePagination(first: number, size: number) {
    return products
      .slice(first, size)
      .map((item: Products) => (
        <WrapItem>
          <ProductCard {...item} />
        </WrapItem>
      ));
  }

  function GetCategories(arrProducts: Products[]) {
    let categoriesArray: (string | undefined)[] = []

    arrProducts.map(({ category }: Products) => {
      if (categoriesArray.indexOf(category) === -1) {
        categoriesArray.push(category)
      }
    })

    return categoriesArray;
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <SideBar categories={GetCategories(products)} />
        <VStack alignItems="flex-start" w="calc(100vw - 20rem)" p={6}>
          <Wrap>
            {slicePagination(pageStart, pageEnd)}
          </Wrap>

          <Pagination
            totalCountOfRegisters={Number(products.length)}
            currentPage={page}
            onPageChange={setPage}
          />
        </VStack>
      </Layout>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const products = await (await fetch('https://fakestoreapi.com/products')).json()

  return {
    props: {
      products
    }
  }
}